### ISSUE TITLE
latex公式识别不太行呢

### ISSUE THREAD

**Issue by QJZX** [PearOCR/pearocr_issue#17]
久被公式折磨，OneNote虽然可以使用手写输入公式，但效率远没ocr高，微软的mathsolver识别不允许粘贴至OneNote（太鸡肋了），第三方api免费的1000次需要有visa（普通学生党不可能通过双币信用卡资产认证的）。哎，希望加入latex或Unicode math公式识别。

**Comment by PearOCR** [comment]
感谢你对pearocr的关注和提出的建议，但是公式识别是一个十分复杂和繁琐的过程，目前的规划中还有很多功能需要优先处理，暂时不考虑增加公式识别
