### ISSUE TITLE
如何在公司内网使用

### ISSUE THREAD

**Issue by Laifang** [PearOCR/pearocr_issue#21]
公司内网缺少 离线本的的ocr工具 如何在公司内网的电脑使用本工具

**Comment by PearOCR** [comment]
目前没有完全离线的版本，不过已经在规划中了，后面会推出

有热心用户提供了一个离线版，可以试一下
https://www.52pojie.cn/forum.php?mod=viewthread&tid=1512578&highlight=pearocr

**Comment by Laifang** [comment]
谢谢
