### ISSUE TITLE
能不能推出白描OCR的合成识别内容，TXT文本功能

### ISSUE THREAD

**Issue by sailing178** [PearOCR/pearocr_issue#25]
视频字幕识别需要这个功能，谢谢开发者

**Comment by PearOCR** [comment]
合成识别内容的功能具体是指什么功能，我下了白描APP找了一下没发现这个功能

**Comment by sailing178** [comment]
> 合成识别内容的功能具体是指什么功能，我下了白描APP找了一下没发现这个功能
1.PC使用的白描网页版，其实就是将识别的所有文字以TEXT的格式输出。
2.不知道能不能介绍一下扫描图片的顺序，就是图片上传后会被排序。因为我OCR视频硬字幕大概是3000张图片左右，如果没有顺序。这些扫描出来的英文可能有点头疼。

**Comment by PearOCR** [comment]
了解，下个版本会增加输出所有图片的问题
扫描图片的排序是根据添加的文件的选择顺序来排序的

**Comment by PearOCR** [comment]
PearOCR 2.0 版本已发布，现已支持导出TXT功能，并且可以设置是否分割文本，如果不需要导出文件，可点击预览按钮进行预览
导出TXT功能在“更多”按钮里
（由于PWA缓存机制，更新后第一次打开还是上一版本，等缓存完毕再次刷新即可使用最新版）
