### ISSUE TITLE
大佬能否考虑下适配

### ISSUE THREAD

**Issue by ifwlzs** [PearOCR/pearocr_issue#28]
全屏的时候挺不错的，但是有些时候我需要小屏进行识别翻译，比如下图所示放在旁边

![image](https://user-images.githubusercontent.com/49548316/135026015-e160be19-7f91-437d-b6e0-812aa0138b59.png)

由于宽度变小，导致翻译的内容还要自己去移动下。有点麻烦。建议大佬可以考虑下加个布局。

判断当前窗口宽度小于某一尺寸后（建议宽度小于800px时候使用，好像原页面设置的最小宽度800px），改下样式，改成上下布局（上面图片粘贴区，下方识别的结果区）

**Comment by PearOCR** [comment]
PearOCR 2.0 版本已发布，现已适配小屏幕
（由于PWA缓存机制，更新后第一次打开还是上一版本，等缓存完毕再次刷新即可使用最新版）
