### ISSUE TITLE
期望增加批量导出功能

### ISSUE THREAD

**Issue by cmldyu** [PearOCR/pearocr_issue#3]
期望能增加批量导出功能，将所有输入图片按顺序保存为1个pdf，或一个txt/docx文档

**Comment by PearOCR** [comment]
感谢建议，后续版本会增加此功能

**Comment by PearOCR** [comment]
批量导出功能已在v1.2版本中更新
详细更新日志见：https://doc.pearocr.com/Contact.html#v1-2
> 由于PWA缓存机制，更新后第一次打开还是上一版本，等缓存完毕再次刷新即可使用最新版
