### ISSUE TITLE
导入图片顺序乱了，另外啥时候整个PC啊

### ISSUE THREAD

**Issue by lj1998008** [PearOCR/pearocr_issue#30]
比如导入12345，导入后不一定是12345的序号了
另外啥时候整个PC啊

**Comment by PearOCR** [comment]
PearOCR 2.0 版本已发布，现在导入时按文件名进行排序
（由于PWA缓存机制，更新后第一次打开还是上一版本，等缓存完毕再次刷新即可使用最新版）
