### ISSUE TITLE
提个问题

### ISSUE THREAD

**Issue by qtxzy** [PearOCR/pearocr_issue#33]
对于透明底的图片型文字,软件好像完全无法识别出来,大概情况见下图,
![image](https://user-images.githubusercontent.com/54807390/137576618-dfb81591-1bca-420d-b827-93a6bacb91d4.png)

**Comment by PearOCR** [comment]
感谢你的反馈，后续会修复该问题

**Comment by PearOCR** [comment]
当前版本已经修复该问题，感谢你的反馈

**Comment by qtxzy** [comment]
great
