### ISSUE TITLE
PWA支持和移动端屏幕适配

### ISSUE THREAD

**Issue by xuangeyouneihan** [PearOCR/pearocr_issue#34]
希望添加对PWA的支持和移动端屏幕的适配，谢谢！

**Comment by KnightJun** [comment]
感谢你对pearocr的关注，pearocr已经支持PWA了，下个版本也会适配移动端屏幕

**Comment by PearOCR** [comment]
感谢你对pearocr的关注，pearocr已经支持PWA了，下个版本也会适配移动端屏幕

**Comment by PearOCR** [comment]
PearOCR 2.0 版本已发布，现已适配移动端屏幕
（由于PWA缓存机制，更新后第一次打开还是上一版本，等缓存完毕再次刷新即可使用最新版）
