### ISSUE TITLE
issue - 读取剪贴板失败

### ISSUE THREAD

**Issue by lsasln** [PearOCR/pearocr_issue#35]
复制微信聊天中的文件会提示读取剪贴板失败，复制桌面的图片 文件也会出现提示，是否微信聊天的图片复制默认是文件形式或者特殊形式？建议增加适配，这个场景比较常用

![image](https://user-images.githubusercontent.com/26127785/140481901-74faf536-a396-4b84-a1e8-f3987467b282.png)

![image](https://user-images.githubusercontent.com/26127785/140482177-288694b9-a33d-480c-a290-2a069394a986.png)

**Comment by PearOCR** [comment]
感谢你对PearOCR的关注，经过测试，如果以【文件】形式复制的话，是没有办法读取的，这是浏览器的机制决定，无法处理。
微信的复制是以【图片】形式复制，是能够正常读取的，请尝试更新微信版本，如果仍旧无法正常读取，希望能附带微信版本和浏览器的版本信息

**Comment by lsasln** [comment]
微信版本 3.4.0.38
浏览器是微软EDGE版本 95.0.1020.44 (官方内部版本) (64 位)
而且我发现微信截图后自动复制的图片是可以读取的，只有在聊天界面点击复制的不可以识别，猜测是微信聊天界面复制的图片可能是【文件】形式

**Comment by PearOCR** [comment]
请问是点击读剪贴板按钮还是用Ctrl+V粘贴的？
由于浏览器的安全策略，在某些场景下读剪贴板按钮是无法获取剪贴板内容，而Ctrl+V是能正常读的
