### ISSUE TITLE
doesn‘t work in long screenshots

### ISSUE THREAD

**Issue by 313069365** [PearOCR/pearocr_issue#4]
it seems don‘t work in long screenshots

**Comment by PearOCR** [comment]
Thanks for your feedback, after testing these is a bug that can't recogniting on long image. I will solve it in the next few versions.

**Comment by PearOCR** [comment]
This bug was fix on version 1.2, you can try the new version. 
it should note that long images consume more time and memory
> The fist time you open it after the version update is still the previous version, wait for the cache to finish refreshing again to use the lastest version
