### ISSUE TITLE
大佬，网站批量识别图片的时候顺序有问题，这个能解决一下吗？

### ISSUE THREAD

**Issue by hfdsadas** [PearOCR/pearocr_issue#41]
比如，我截了某个电影的一些字幕图片，想要用PearOCR识别一下。图片文件的顺序是按照电影推进顺序排列的，正序。但是导入到网站之后，它会先识别最后一个图片，然后依次往前识别。也就是说，识别顺序变成相反的了，最后导出的文档文本也是逆序的，请问这个能解决一下吗，谢谢。

**Comment by hfdsadas** [comment]
我刚发现把文件排列顺序改为递减排列，再传到网站上最终顺序就正了……   
所以现在也没啥问题了……     网站识别得挺好的

**Comment by shaltama** [comment]
我专门为此让人工智能给我写了一个PDF页面颠倒的工具，可以用一下看看：https://github.com/shaltama/PDF-Page-Reverser/releases/tag/v0.1.0
