### ISSUE TITLE
Firefox 不支持 navigator.clipboard.read

### ISSUE THREAD

**Issue by Landius** [PearOCR/pearocr_issue#5]
![图片](https://user-images.githubusercontent.com/11910028/130625957-85de289d-c871-4b5a-92b8-045ef6064900.png)

没法直接截图再粘贴了，只能上传文件识别...😢
把 `div` 设为 `contentEditable="true"` 让用户粘贴图片再读 `img` 应该可以解决

**Comment by PearOCR** [comment]
感谢反馈，问题已确认，firefox对剪贴板这一块的限制比较大，我试试你提供的方法看看能不能提高一下这部分的体验

**Comment by PearOCR** [comment]
Firefox剪贴板问题已经在v1.2版本做出了改善，由于Firefox的限制，没办法通过点击按钮来读取剪贴板，不过可以通过主动按下粘贴键来读取剪贴板的图片
详细更新日志见：https://doc.pearocr.com/Contact.html#v1-2
> 由于PWA缓存机制，更新后第一次打开还是上一版本，等缓存完毕再次刷新即可使用最新版
