### ISSUE TITLE
请问项目开源协议以及申请二次开发授权

### ISSUE THREAD

**Issue by aduo** [PearOCR/pearocr_issue#9]
Hi Contributors:
     咨询下https://github.com/PearOCR/website 项目的License是什么, 是否允许移植其他平台或者二次开发? 
     我想把这个优秀的项目做成utools插件. 本人保证所有基于PearOCR的项目都以非盈利为目的, 代码开源, 保留PearOCR署名, 遵守License. 感谢~

**Comment by PearOCR** [comment]
感谢你的为该项目做出的工作，保留PearOCR署名，不要删减项目的内容信息即可
